[package]
name = "migrator"
version = "0.0.1"
edition = "2021"

[dependencies]
serde = "1.0.215"
sqlx = { version = "0.8.2", features = ["postgres", "runtime-tokio"] }
tokio = { version = "1.41.1", features = ["full"] }
toml = "0.8.19"
